

#pragma checksum "C:\Program Files (x86)\Jenkins\jobs\HomeBuh\workspace\MyBuh\MyBuh\Balans.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "09180D26305C5EE5F0978366D5732DE3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuh
{
    partial class BalansPage : global::Windows.UI.Xaml.Controls.Page
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.ListView listview; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.ComboBox AccountCmbBx; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.TextBox SummTxt; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.TextBox dtxt1; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.TextBox dtxt2; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.TextBox dtxt3; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.Button CommitButton; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.Button SaveButton; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.Button DeleteButton; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.ComboBox CatCmbBx; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.TextBox Commenttxt; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private global::Windows.UI.Xaml.Controls.Button Назад; 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        private bool _contentLoaded;

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 4.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent()
        {
            if (_contentLoaded)
                return;

            _contentLoaded = true;
            global::Windows.UI.Xaml.Application.LoadComponent(this, new global::System.Uri("ms-appx:///Balans.xaml"), global::Windows.UI.Xaml.Controls.Primitives.ComponentResourceLocation.Application);
 
            listview = (global::Windows.UI.Xaml.Controls.ListView)this.FindName("listview");
            AccountCmbBx = (global::Windows.UI.Xaml.Controls.ComboBox)this.FindName("AccountCmbBx");
            SummTxt = (global::Windows.UI.Xaml.Controls.TextBox)this.FindName("SummTxt");
            dtxt1 = (global::Windows.UI.Xaml.Controls.TextBox)this.FindName("dtxt1");
            dtxt2 = (global::Windows.UI.Xaml.Controls.TextBox)this.FindName("dtxt2");
            dtxt3 = (global::Windows.UI.Xaml.Controls.TextBox)this.FindName("dtxt3");
            CommitButton = (global::Windows.UI.Xaml.Controls.Button)this.FindName("CommitButton");
            SaveButton = (global::Windows.UI.Xaml.Controls.Button)this.FindName("SaveButton");
            DeleteButton = (global::Windows.UI.Xaml.Controls.Button)this.FindName("DeleteButton");
            CatCmbBx = (global::Windows.UI.Xaml.Controls.ComboBox)this.FindName("CatCmbBx");
            Commenttxt = (global::Windows.UI.Xaml.Controls.TextBox)this.FindName("Commenttxt");
            Назад = (global::Windows.UI.Xaml.Controls.Button)this.FindName("Назад");
        }
    }
}



